spring:
  application:
    name: orchestrator-worker

server:
  port: 8084

orchestrator:
  order-base-url: http://localhost:8081
  payment-base-url: http://localhost:8082
  inventory-base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
